Pro09/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('main/',views.main,name="main"),
    path('myapp/',include("myapp.urls")),
]

myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('motto/',views.motto,name="Motto"),
    path('profile/',views.profile,name="profile"),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def motto(request):
    return HttpResponse("<h1>Project is ready to launch</h1>")

def main(request):
    return render(request,"main.html")

def home(request):
    return render(request,"myapp/home.html")

def profile(request):
    name="Superman Man of Steel"
    return render(request,"myapp/profile.html",{'name':name})

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block title %}
        <title>Main Page</title>
    {% endblock %}

    <!--CSS Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!--JavaScript-->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</head>
<body>
  <!--Top-->
  {% include "partials/_topbar.html" %}
  
  <!--Navbar-->
  {% include "partials/_navbar.html" %}
  
    {% block content %}
      <div class="container">
        <div class="jumbotron">
          <h1>Welcome to Tron Rider's Page</h1>
          <img class="mainimg" src="{% static 'images/tron.gif' %}" alt="No Image Found">
        </div>
      </div>
    {% endblock %}

    <!--Footer-->
    {% include "partials/_footbar.html" %}

</body>
</html>

templates/myapp/home.html
{% extends "main.html" %}
{% load static %}
{% block title %}
    <title>Home Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h3>Welcome to </h3>
            <img class="homeimg" src="{% static 'images/tron legacy logo.gif' %}" alt="">
        </div>
      </div>
{% endblock %}

templates/myapp/profile.html
{% extends "main.html" %}
{% load static %}
{% block title %}
    <title>Profile Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h2>Welcome to {{name}}'s Profile page</h2>
            <img class="profileimg" src="{% static 'images/superman.jpg' %}" alt="No Image Found">
        </div>
      </div>
{% endblock %}

templates/partials/_footbar.html
{% load static %}
<!-- footer -->
<div class="alert alert-danger" role="alert">
    <center>Have enough courage to start and enough heart to finish. <img class="logo" src="{% static 'images/djangologo.png' %}" alt="No Image Found"></center>
  </div>

templates/partials/_navbar.html
<!-- navbar -->
<div class="container">
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'home' %}">Tron</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'main' %}">Legacy</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:profile' %}">Profile</a>
        </li>      
    </ul>
</div>

templates/partials/_topbar.html
{% load static %}
<!-- topbar -->
<div class="alert alert-danger" role="alert">
    <center><img class ="logo" src="{% static 'images/djangologo.png' %}" alt="No Image Found"> 
        Change the game, don’t let the game change you.</center>
    
 </div>